hsv_filter:
  ros__parameters:
    use_sim_time: false
    min_h: 92
    max_h: 132
    min_s: 0
    max_s: 203
    min_v: 109
    max_v: 245

head_controller:
  ros__parameters:
    pan_joint_name: head_1_joint
    tilt_joint_name: head_2_joint
    use_sim_time: false
    pan_pid_min_ref: 0.0
    pan_pid_max_ref: 1.0
    pan_pid_min_output: 0.0
    pan_pid_max_output: 0.3
    tilt_pid_min_ref: 0.0
    tilt_pid_max_ref: 1.0
    tilt_pid_min_output: 0.0
    tilt_pid_max_output: 0.3
    pan_limit: 1.3
    tilt_limit: 0.92
    use_ipc: true

depth_estimator:
  ros__parameters:
    use_sim_time: false
    use_ipc: true